INSERT INTO drug ( drug_name ) VALUES ( 'Levothyroxine');
INSERT INTO drug ( drug_name ) VALUES ( 'Lisinopril');
INSERT INTO drug ( drug_name ) VALUES ( 'Atorvastatin');
INSERT INTO drug ( drug_name ) VALUES ( 'Metformin');
INSERT INTO drug ( drug_name ) VALUES ( 'Amlodipine');
INSERT INTO drug ( drug_name ) VALUES ( 'Metoprolol');
INSERT INTO drug ( drug_name ) VALUES ( 'Omeprazole');
INSERT INTO drug ( drug_name ) VALUES ( 'Simvastatin');
INSERT INTO drug ( drug_name ) VALUES ( 'Soma');
INSERT INTO drug ( drug_name ) VALUES ( 'Skooma');
INSERT INTO drug ( drug_name ) VALUES ( 'Neuroin');
INSERT INTO drug ( drug_name ) VALUES ( 'Repressitol');
INSERT INTO drug ( drug_name ) VALUES ( 'Senzu Beans');
INSERT INTO drug ( drug_name ) VALUES ( 'Felix Felicis');
INSERT INTO drug ( drug_name ) VALUES ( 'Melange');
INSERT INTO drug ( drug_name ) VALUES ( 'Nepenthe');
INSERT INTO drug ( drug_name ) VALUES ( 'Azoth');
INSERT INTO drug ( drug_name ) VALUES ( 'Manna');
INSERT INTO drug ( drug_name ) VALUES ( 'Ambrosia');
INSERT INTO drug ( drug_name ) VALUES ( 'Glitterstim');