INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('90746', 'Hep-B vaccination given', 150.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('90632', 'Basic check up for stomach pain', 125.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('93001', 'Cardiovascular test done', 490.00);
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('71020', 'Chest X-ray done', 450.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('80048', 'Urea blood test done', 275.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('91035', 'Intestine examination', 775.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('76705', 'Ultrasound test', 675.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('20610', 'Basic check up for shoulder pain', 210.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('81001', 'Urinalysis procedure done', 410.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('82947', 'Glucose tested', 375.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('82465', 'Cholesterol test done', 450.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('47562', 'Gallbladder removed', 1025.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('78099', 'Basic check up for migrane', 275.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('16030', 'Treatment for skin burns', 890.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('90477', 'Hep-C vaccine given', 175.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('99499', 'Referral for sleep therapy', 220.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('19301', 'Lumpectomy procedure done', 2450.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('42900', 'Pharynx prcoedure done', 4550.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('1916', 'Local anesthesia given', 3200.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('42825', 'Tonsillectomy procedure done', 7500.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('43235', 'Gastrointestinal endoscopy', 3245.00 );
INSERT INTO medical_procedure (procedure_id, name, price) VALUES ('47563', 'Cholecystectomy', 6535.00 );