INSERT INTO security_question ( question ) VALUES ( 'What city were you born in?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the first name of your favorite schoolteacher?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the short name of the high school you attended?	' );
INSERT INTO security_question ( question ) VALUES ( 'Which year did you graduate from high school?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the first name of your favorite singer?' );
INSERT INTO security_question ( question ) VALUES ( 'What is your favorite color?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the first name of your mother’s sister?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the first name of your father’s brother?' );
INSERT INTO security_question ( question ) VALUES ( 'In which year, your immediate elder sibling was born?' );
INSERT INTO security_question ( question ) VALUES ( 'In which year, your immediate younger sibling was born?' );
INSERT INTO security_question ( question ) VALUES ( 'What are the last four digits of your current phone number?' );
INSERT INTO security_question ( question ) VALUES ( 'Which city would you like to visit as your dream vacation?' );
INSERT INTO security_question ( question ) VALUES ( 'Which country would you to visit as your dream vacation?' );
INSERT INTO security_question ( question ) VALUES ( 'What was your birth month and date?' );
INSERT INTO security_question ( question ) VALUES ( 'What is your closest friend’s nickname?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the first name of your first roommate?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the name of the college you attended first?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the name of the course you liked the most in your first year of college?' );
INSERT INTO security_question ( question ) VALUES ( 'What is the name of the course you liked the most in your first year of high school?' );
INSERT INTO security_question ( question ) VALUES ( 'What was the make of your first car?' );
INSERT INTO security_question ( question ) VALUES ( 'In which year, you first flew in an airplane?' );
